### ISSUE TITLE
Queue not posting in random order.

### ISSUE THREAD

**Issue by N3UJJ** [bdsmlr-development/bdsmlr-updates#14]
Hey BDSMLR, why id mu queue not posting in random order any more?

**Comment by jenevieveee** [comment]
The staff is aware of the problem and there are multiple (internal) bug reports addressing that. Unfortunately, right now all of the efforts are going into keeping the site running at a basic level, so nice-to-haves like the queue randomization are on the back burner until they get more staff (See May 5th update -- more staff is starting the week of May 17th.)

**Comment by N3UJJ** [comment]
I'm curious why it worked a while ago, and now is not working.
